enabled: true
replicaCount: 1
image:
  repository: gateway-service
  tag: "latest"
  imagePullPolicy: Never
service:
  port: 8080

# Конфигурация Spring (не хранить секреты здесь!)
config:
  spring:
    application:
      name: gateway-service
    r2dbc:
      url: "r2dbc:postgresql://bank-platform-postgres:5432/bank?currentSchema=users"
    security:
      oauth2:
        client:
          registration:
            gateway-client:
              client-id: gateway-service
              client-secret: "${KEYCLOAK_CLIENT_SECRET}"  # Берём из env
          provider:
            keycloak:
              issuer-uri: http://192.168.0.140:8090/realms/bank

# Секреты
gateway-service:
  secrets:
    keycloakSecret: gateway-service-keycloak-secret
    dbCredentials: gateway-service-db-credentials

