apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-service.fullname" . }}
  labels:
    app: {{ include "gateway-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "gateway-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gateway-service.name" . }}
    spec:
      containers:
        - name: {{ include "gateway-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}

          # Конфигурация через ConfigMap/Secret
          envFrom:
            - configMapRef:
                name: {{ include "gateway-service.fullname" . }}-config

          # Подключение реальных секретов
          env:
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values "gateway-service" "secrets" "dbCredentials" }}
                  key: username
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values "gateway-service" "secrets" "dbCredentials" }}
                  key: password
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values "gateway-service" "secrets" "keycloakSecret" }}
                  key: client-secret

          volumeMounts:
            - name: config
              mountPath: /config

      volumes:
        - name: config
          configMap:
            name: {{ include "gateway-service.fullname" . }}-config