# {{- if .Values.externalSecrets.enabled }}
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: {{ .Release.Name }}-account-service-secret
# spec:
#   refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
#   secretStoreRef:
#     name: {{ .Values.secretStore.name }}
#     kind: {{ .Values.secretStore.kind | default "SecretStore" }}
#   target:
#     name: {{ .Release.Name }}-account-service-secret
#     creationPolicy: Owner
#   data:
# {{- range .Values.externalSecrets.data }}
#     - secretKey: {{ .secretKey }}
#       remoteRef:
#         key: {{ .remoteRef.key }}
#         property: {{ .remoteRef.property }}
# {{- end }}
# {{- end }}