# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ include "gateway-service.fullname" . }}-secret
# type: Opaque
# stringData:
#   SPRING_R2DBC_PASSWORD: {{ .Values.config.spring.r2dbc.password | quote }}
