apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaffka-service.fullname" . }}
  labels:
    {{- include "kaffka-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "kaffka-service.fullname" . }}
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaffka-service.fullname" . }}-headless
  labels:
    {{- include "kaffka-service.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "kaffka-service.fullname" . }}
  ports:
    - name: controller
      port: 9093
      targetPort: 9093