enabled: true
replicaCount: 1
image:
  repository: transfer-service
  tag: "latest"
  imagePullPolicy: Never
service:
  port: 8086

config: {}  

secretStore:
  create: false

externalSecrets:
  enabled: false