enabled: true
replicaCount: 1
image:
  repository: transfer-service
  tag: "latest"
  imagePullPolicy: Never
service:
  port: 8086

config: {}  # оставляем пустым, больше нет r2dbc или паролей

# ExternalSecrets можно оставить, если нужны другие секреты
secretStore:
  create: false

externalSecrets:
  enabled: false