enabled: true
replicaCount: 1
image:
  repository: notification-service
  tag: "latest"
  imagePullPolicy: Never
service:
  port: 8087

config: {}  

secretStore:
  create: false

externalSecrets:
  enabled: false