spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        registration:
          gateway-user:                # registrationId (локальное имя)
            provider: keycloak
            client-id: gateway-service       # <-- фактический clientId в Keycloak
            client-secret: "${KEYCLOAK_CLIENT_SECRET}"  # предаем в Secret для keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/gateway-service"
            scope:
              - openid
              - profile
              - email

          gateway-client:              # локальное имя для client_credentials
            provider: keycloak
            client-id: gateway-service       # <-- тот же клиент в Keycloak
            client-secret: "${KEYCLOAK_CLIENT_SECRET}"  # предаем в Secret для keycloak
            authorization-grant-type: client_credentials
            scope:
              - openid

        provider:
          keycloak:
            issuer-uri: http://192.168.0.140:8090/realms/bank
            # можно не указывать остальные поля, issuer-uri подставит их автоматически

      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.140:8090/realms/bank

  r2dbc:
    url: r2dbc:postgresql://bank-platform-postgres:5432/bank?currentSchema=users
  
  webflux:
    static-path-pattern: "/static/**"
          
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: cash-service
          uri: http://bank-platform-cash-service:8083
          predicates:
            - Path=/api/cash/**
          filters:
            - StripPrefix=1

        - id: account-service
          uri: http://bank-platform-account-service:8082
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1

        - id: exchange-service
          uri: http://bank-platform-exchange-service:8084
          predicates:
            - Path=/api/exchange/**
          filters:
            - StripPrefix=1

        - id: exchangeGenerator
          uri: http://bank-platform-exchangeGenerator:8085
          predicates:
            - Path=/api/exchangeGenerator/**
          filters:
            - StripPrefix=1

        - id: transfer-service
          uri: http://bank-platform-transfer-service:8084
          predicates:
            - Path=/api/transfer/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://bank-platform-notification-service:8087
          predicates:
            - Path=/api/notifications/**, /notifications/**
          filters:
            - StripPrefix=1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

clients:
  account:
    base-url: http://bank-platform-account-service:8082
  cash:
    base-url: http://bank-platform-cash-service:8083
  exchange:
    base-url: http://bank-platform-exchange-service:8084
  transfer:
    base-url: http://bank-platform-transfer-service:8086
  notification:
    base-url: http://bank-platform-notification-service:8087

keycloak:
  server-url: http://192.168.0.140:8090
  realm: bank
  client-id: gateway-service
  client-secret: "${KEYCLOAK_CLIENT_SECRET}"

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.security.oauth2.client: DEBUG