spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        registration:
          gateway-user:                # registrationId (локальное имя)
            provider: keycloak
            client-id: gateway-service       # <-- фактический clientId в Keycloak
            client-secret: "${KEYCLOAK_CLIENT_SECRET}"  # предаем в Secret для keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/gateway-service"
            scope:
              - openid
              - profile
              - email

          gateway-client:              # локальное имя для client_credentials
            provider: keycloak
            client-id: gateway-service       # <-- тот же клиент в Keycloak
            client-secret: "${KEYCLOAK_CLIENT_SECRET}"  # предаем в Secret для keycloak
            authorization-grant-type: client_credentials
            scope:
              - openid

        provider:
          keycloak:
            issuer-uri: http://192.168.0.140:8090/realms/bank
            # можно не указывать остальные поля, issuer-uri подставит их автоматически

      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.140:8090/realms/bank

  r2dbc:
    url: r2dbc:postgresql://bank-platform-postgres:5432/bank?currentSchema=users
  
  webflux:
    static-path-pattern: "/static/**"
  
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://bank-platform-zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

logging:
  level:
    zipkin2: DEBUG
    zipkin2.reporter: DEBUG
    brave: DEBUG
    io.micrometer.tracing: DEBUG
    org.springframework.boot.actuate.autoconfigure.tracing: DEBUG

server:
  port: 8080



clients:
  account:
    base-url: http://bank-platform-account-service:8082
  cash:
    base-url: http://bank-platform-cash-service:8083
  exchange:
    base-url: http://bank-platform-exchange-service:8084
  transfer:
    base-url: http://bank-platform-transfer-service:8086
  notification:
    base-url: http://bank-platform-notification-service:8087

keycloak:
  server-url: http://192.168.0.140:8090
  realm: bank
  client-id: gateway-service
  client-secret: "${KEYCLOAK_CLIENT_SECRET}"
  
app:
  logs:
    kafka:
      env: dev
      topic: bank-platform-logs

