# {{- if .Values.secretStore.create }}
# apiVersion: external-secrets.io/v1
# kind: SecretStore
# metadata:
#   name: {{ .Values.secretStore.name }}
#   namespace: {{ .Release.Namespace }}
# spec:
#   provider:
#     kubernetes:
#       # namespace, где лежат секреты, которые ExternalSecret будет читать
#       remoteNamespace: default
# {{- end }}