apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-generator.fullname" . }}-config
data:
  application.yml: |
    spring:
      application:
        name: exchange-generator

      main:
        web-application-type: none
        allow-bean-definition-overriding: true

      kafka:
        bootstrap-servers: {{ .Values.global.kafka.bootstrapServers | quote }}
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          acks: all
          retries: 5
          properties:
            enable.idempotence: true

    app:
      kafka:
        topics:
          exchange-rates: exchange.rates

    exchange:
      api-url: "https://open.er-api.com/v6/latest/RUB"
      update-interval-ms: 60000

    server:
      port: 8085

    management:
      endpoints:
        web:
          exposure:
            include: health,info