apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exchange-generator.fullname" . }}
  labels:
    app: {{ include "exchange-generator.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "exchange-generator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "exchange-generator.name" . }}
    spec:
      containers:
        - name: {{ include "exchange-generator.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "exchange-generator.fullname" . }}-config
          volumeMounts:
            - name: config
              mountPath: /app/config

          resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"

          startupProbe:
            exec:
              command: ["sh","-c","ps -o comm= -p 1 | grep -qi java"]
            failureThreshold: 30
            periodSeconds: 5

          livenessProbe:
            exec:
              command: ["sh","-c","ps -o comm= -p 1 | grep -qi java"]
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            exec:
              command: ["sh","-c","ps -o comm= -p 1 | grep -qi java"]
            initialDelaySeconds: 5
            periodSeconds: 5

      volumes:
        - name: config
          configMap:
            name: {{ include "exchange-generator.fullname" . }}-config