apiVersion: v1
kind: Service
metadata:
  name: {{ include "exchange-generator.fullname" . }}
  labels:
    app: {{ include "exchange-generator.name" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 30085   # <--- добавь этот параметр
  selector:
    app: {{ include "exchange-generator.name" . }}