apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    app: {{ include "transfer-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "transfer-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "transfer-service.name" . }}
    spec:
      containers:
        - name: {{ include "transfer-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "transfer-service.fullname" . }}-config
          volumeMounts:
            - name: config
              mountPath: /config

      volumes:
        - name: config
          configMap:
            name: {{ include "transfer-service.fullname" . }}-config