replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.54.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

scrapeInterval: 15s
evaluationInterval: 15s

# Для prometheus-community Helm chart
prometheus:
  prometheusSpec:
    extraArgs:
      - '--web.external-url=http://localhost/prometheus'
      - '--web.route-prefix=/prometheus'
      - '--web.enable-lifecycle'
    
    # Если используется sidecar для конфигов
    configMaps:
      - prometheus-config
    
  # Конфигурация Ingress
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - localhost
    paths:
      - /prometheus(/|$)(.*)