apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /zipkin
        pathType: Prefix
        backend:
          service:
            name: bank-platform-zipkin
            port:
              number: 9411
      paths:
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: bank-platform-prometheus
            port:
              number: 9090
      - path: /bank
        pathType: Prefix
        backend:
          service:
            name: bank-platform-gateway-service
            port:
              number: 8080
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: bank-platform-gateway-service
      #       port:
      #         number: 8080     