apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /zipkin
        pathType: Prefix
        backend:
          service:
            name: bank-platform-zipkin
            port:
              number: 9411

      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: bank-platform-prometheus
            port:
              number: 9090

      - path: /bank
        pathType: Prefix
        backend:
          service:
            name: bank-platform-gateway-service
            port:
              number: 8080

      # OAuth2 редиректы идут без /bank, поэтому прокидываем /oauth2 на gateway
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: bank-platform-gateway-service
            port:
              number: 8080

      # зависит от конфигурации security
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: bank-platform-gateway-service
            port:
              number: 8080
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: bank-platform-grafana
            port:
              number: 3000
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: bank-platform-kibana
            port:
              number: 5601
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bank-platform-gateway-service
            port:
              number: 8080     