apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account-service.fullname" . }}
  labels:
    app: {{ include "account-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "account-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "account-service.name" . }}
    spec:
      containers:
        - name: {{ include "account-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}

          # Конфигурация через ConfigMap/Secret
          envFrom:
            - configMapRef:
                name: {{ include "account-service.fullname" . }}-config
            - secretRef:
                name: {{ include "account-service.fullname" . }}-secret

          # Подключение реальных секретов
          env:
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values "account-service" "secrets" "dbCredentials" }}
                  key: username
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values "account-service" "secrets" "dbCredentials" }}
                  key: password
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://bank-platform-keycloak:8095/realms/bank"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI
              value: "http://bank-platform-keycloak:8095/realms/bank/protocol/openid-connect/token"

            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values "account-service" "secrets" "keycloakSecret" }}
                  key: client-secret

          volumeMounts:
            - name: config
              mountPath: /app/config

          startupProbe:
            tcpSocket:
              port: 8082
            failureThreshold: 30
            periodSeconds: 5
            
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 5

          volumeMounts:
            - name: config
              mountPath: /app/config

      volumes:
        - name: config
          configMap:
            name: {{ include "account-service.fullname" . }}-config