apiVersion: v1
kind: Service
metadata:
  name: {{ include "account-service.fullname" . }}
  labels:
    app: {{ include "account-service.name" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 30082   
  selector:
    app: {{ include "account-service.name" . }}