enabled: true
replicaCount: 1
image:
  repository: cash-service
  tag: "latest"
  imagePullPolicy: Never
service:
  port: 8083

config: {} 

secretStore:
  create: false

externalSecrets:
  enabled: false