spring:
  application:
    name: exchange-generator

app:
  kafka:
    topics:
      exchange-rates: exchange.rates
  logs:
    kafka:
      env: dev
      topic: bank-platform-logs

server:
  port: 8085

# Только внешний API
exchange:
  api-url: https://open.er-api.com/v6/latest/RUB
  update-interval-ms: 60000   # раз в минуту



