apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kibana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kibana
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.elasticsearch.hosts | quote }}
            - name: NODE_OPTIONS
              value: {{ .Values.nodeOptions | quote }}

            - name: XPACK_SECURITY_ENCRYPTIONKEY
              value: {{ .Values.encryptionKeys.security | quote }}
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              value: {{ .Values.encryptionKeys.savedObjects | quote }}
            - name: XPACK_REPORTING_ENCRYPTIONKEY
              value: {{ .Values.encryptionKeys.reporting | quote }}

            - name: SERVER_BASEPATH
              value: "/kibana"
            - name: SERVER_REWRITEBASEPATH
              value: "true"

          readinessProbe:
            httpGet:
              path: /kibana/api/status
              port: 5601
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probe.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: /kibana/api/status
              port: 5601
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probe.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}