apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-kibana
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 5601