apiVersion: v2
name: elk
type: application
version: 0.1.0
appVersion: "8.x"
dependencies:
  - name: elasticsearch
    version: 0.1.0
    repository: "file://./charts/elasticsearch"
    condition: elasticsearch.enabled

  - name: logstash
    version: 0.1.0
    repository: "file://./charts/logstash"
    condition: logstash.enabled

  - name: kibana
    version: 0.1.0
    repository: "file://./charts/kibana"
    condition: kibana.enabled