mode: single
env: dev

elasticsearch:
  enabled: true
  replicaCount: 1
  service:
    port: 9200

kibana:
  enabled: true
  replicaCount: 1
  service:
    port: 5601

logstash:
  enabled: true
  replicaCount: 1

  # куда подключаться
  kafka:
    bootstrapServers: "kaffka-service:9092"
    topic: "bank-platform-logs"
    groupId: "logstash-bank-platform"

  elasticsearch:
    hosts: "http://bank-platform-elasticsearch:9200"  # зависит от имени release/сервиса

  filter:
    enabled: true
    envFilterEnabled: true
    envValue: dev

  debugStdout: false

  fingerprintKey: "change-me-in-secret" # лучше вынести в Secret

  


