postgres:
  enabled: true
  replicaCount: 1
  postgresUser: postgres
  postgresPassword: secret_pass
  postgresDatabase: bank
  storage:
    size: 1Gi

notificationService:
  enabled: true
  replicaCount: 1
  image:
    repository: notification-service
    tag: "latest"
  service:
    port: 8087

accountService:
  enabled: true
  replicaCount: 1
  image:
    repository: account-service
    tag: "latest"
    imagePullPolicy: Never
  service:
    port: 8082
  config:
    spring:
      r2dbc:
        url: "r2dbc:postgresql://bank-platform-postgres:5432/bank?currentSchema=account"
        username: postgres
        password: secret_pass

cashService:
  enabled: true
  replicaCount: 1
  image:
    repository: cash-service
    tag: "latest"
  service:
    port: 8083

gatewayService:
  enabled: true
  replicaCount: 1
  image:
    repository: gateway-service
    tag: "latest"
  service:
    port: 8080

exchangeService:
  enabled: true
  replicaCount: 1
  image:
    repository: exchange-service
    tag: "latest"
  service:
    port: 8084

exchangeGenerator:
  enabled: true
  replicaCount: 1
  image:
    repository: exchange-generator
    tag: "latest"
  service:
    port: 8085

transferService:
  enabled: true
  replicaCount: 1
  image:
    repository: transfer-service
    tag: "latest"
  service:
    port: 8086

kaffka-service:
  image:
    repository: apache/kafka
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: ""
  service:
    port: 9092
  kafka:
    advertisedListeners: "PLAINTEXT://kaffka-service:9092"
    controllerQuorumVoters: "1@kaffka-service-0.kaffka-service-headless:9093"

global:
  kafka:
    bootstrapServers: "kaffka-service:9092"
  env: dev

zipkin:
  enabled: true
  replicaCount: 1
  image:
    repository: openzipkin/zipkin   # Образ для Zipkin
    tag: "3.5"                      # Версия Zipkin
    pullPolicy: IfNotPresent         # Стратегия подкачки
  service:
    port: 9411

prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.54.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090

grafana:
  enabled: true

