apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}-exporter
  labels:
    app: {{ include "postgres.fullname" . }}-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres.fullname" . }}-exporter
  template:
    metadata:
      labels:
        app: {{ include "postgres.fullname" . }}-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.15.0
          ports:
            - name: metrics
              containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://{{ .Values.postgresUser }}:{{ .Values.postgresPassword }}@{{ include "postgres.fullname" . }}:5432/{{ .Values.postgresDatabase }}?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-exporter
  labels:
    app: {{ include "postgres.fullname" . }}-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
  selector:
    app: {{ include "postgres.fullname" . }}-exporter