apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . | default (printf "%s-postgres" .Release.Name) }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "postgres.fullname" . | default (printf "%s-postgres" .Release.Name) }}
  clusterIP: None