{{- if .Values.fingerprintKeySecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fingerprintKeySecret.name }}
type: Opaque
stringData:
  {{ .Values.fingerprintKeySecret.key }}: {{ .Values.fingerprintKeySecret.value | quote }}
{{- end }}